export const DEFAULT_HEADER_CONFIG = {
  logoSize:            64,
  logoPosition:        'center',
  logoOffsetX:         0,
  logoOffsetY:         0,
  schoolNameSize:      22,
  schoolNameAlign:     'center',
  schoolNameOffsetX:   0,
  schoolNameOffsetY:   0,
  schoolNameCurved:    false,
  schoolNameCurveDepth: 28,
  addressSize:         11,
  addressAlign:        'center',
  addressOffsetX:      0,
  addressOffsetY:      0,
  metaSize:            10,
  metaAlign:           'center',
  metaOffsetX:         0,
  metaOffsetY:         0,
  titleSize:           16,
  titleAlign:          'center',
  titleOffsetX:        0,
  titleOffsetY:        0,
  paddingTop:          10,
  showLogo:            true,
  showAddress:         true,
  showMeta:            true,
}

export const HEADER_ALIGNMENTS = ['left', 'center', 'right']
